// Role enumeration aligned with the RBAC module described in the product vision.
export enum UserRole {
  SUPER_ADMIN = "SUPER_ADMIN",
  IR_DIRECTOR = "IR_DIRECTOR",
  IR_COORDINATOR = "IR_COORDINATOR",
  DEPARTMENT_COORDINATOR = "DEPARTMENT_COORDINATOR",
  FACULTY_MENTOR = "FACULTY_MENTOR",
  ADMISSION_TEAM = "ADMISSION_TEAM",
  VISA_TEAM = "VISA_TEAM",
  FINANCE_TEAM = "FINANCE_TEAM",
  EVENT_MANAGER = "EVENT_MANAGER",
  OUTBOUND_STUDENT = "OUTBOUND_STUDENT",
  INCOMING_STUDENT = "INCOMING_STUDENT",
  PARTNER_REPRESENTATIVE = "PARTNER_REPRESENTATIVE"
}
